title:            Ania Rybacka
description:      vocalist | psychologist | composer
logo:             Ania logo.png

disqus_shortname:
#Comment out url when working locally to resolve base urls correctly
url:              http://aniarybacka.com

# Owner/author information
owner:
  name:           Ania Rybacka
  avatar:         afro3.jpg
  email:          ann.rybacka@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  facebook:       aniarybackamusic
  github:
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:
  youtube:        BlueberryMusik

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: News
    url: /articles
  - title: Bio
    url: /about
  - title: Concerts
    url: /concerts
  - title: Media
    url: /media
  - title: Projects
    url: /projects
  - title: Contact
    url: /contact
  - title: Facebook
    url: https://www.facebook.com/aniarybackamusic
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Copenhagen
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec"]
